
# http://docs.travis-ci.com/user/deployment/custom/
# http://docs.travis-ci.com/user/build-configuration
# http://docs.travis-ci.com/user/encrypting-files/

language: java
jdk:
  - oraclejdk8
#  - oraclejdk7
#  - openjdk7
#  - openjdk6

before_install: openssl aes-256-cbc -K $encrypted_7d767fcac9aa_key -iv $encrypted_7d767fcac9aa_iv -in settings-obf.xml.enc -out settings-obf.xml -d
after_success: mvn deploy --settings settings-obf.xml
